name: Publish UPM Package

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
 deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    
    - uses: actions/checkout@master
    - name: Copy the README
      run: |
          cp "README.md" "./Assets/Plugins/${GITHUB_REPOSITORY#*/}/README.md"
    - name: Copy the LICENSE
      run: |
          cp "LICENSE" "./Assets/Plugins/${GITHUB_REPOSITORY#*/}/LICENSE"
    - name: Commit files
      run: |
        git config --local user.email ${{secrets.ADMIN_MAIL}}
        git config --local user.name ${{secrets.ADMIN_NAME}}
        git add .
        git commit -m "Update README.md and LICENSE" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Any prerequisite steps
    - uses: actions/checkout@master

    # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: upm
        FOLDER: Assets/Plugins/${GITHUB_REPOSITORY#*/}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_EMPTY_COMMITS: true
        MESSAGE: "{msg}"
